config/routes.rb
Rails.application.routes.draw do
  root 'website#index'

  get 'welcome/index'
  get '/login' => "website#login", as: "login"
  post '/logout' => "website#logout", as: "logout"

  resources :website, only: [:index] do
    collection do
      post :submit_login
    end
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :question
  belongs_to :user

  scope :from_public_questions, -> {joins(:question).where(questions: {private: false})}

end

app/models/question.rb
class Question < ActiveRecord::Base

  has_many :answers, dependent: :destroy
  belongs_to :user

  scope :not_private, -> {where(private: false)}

end

app/models/tenant.rb
class Tenant < ActiveRecord::Base

  before_create :generate_api_key

  validates :name, presence: true

  def add_views_count
    self.update_attribute(:views, (views + 1) )
  end

  def self.all_tenant_views
    views = 0
    self.all.map{|x| views += x.views}
    return views
  end

  private

  def generate_api_key
    self.api_key = SecureRandom.hex(16)
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :questions, dependent: :destroy, inverse_of: :asker
  has_many :answers,   dependent: :destroy, inverse_of: :answerer

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :verify_tenant_api_key, if: "request.format.html?"

  def verify_tenant_api_key
    if session[:tenant_api_key].present? && params[:api_key].present? && session[:tenant_api_key] == params[:api_key]
      tenant = Tenant.find_by(api_key: session[:tenant_api_key])
      tenant.add_views_count if tenant.present?
      @hash_of_additional_params = {api_key: session[:tenant_api_key]} # Will be used on `url_for` ApplicationHelper
    else
      session[:tenant_api_key] = nil
      redirect_to login_path
    end
  end
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
  skip_before_action :verify_tenant_api_key, only: [:login, :submit_login, :logout]
  before_action :all_data, except: [:login, :submit_login, :logout]

  def login
    return redirect_to root_path if session[:tenant_api_key].present?
  end

  def submit_login
    if (@tenant = Tenant.find_or_create_by(name: tenant_params[:name]))
      session[:tenant_api_key] = @tenant.api_key
      redirect_to root_path(api_key: session[:tenant_api_key])
    else
      render :login
    end
  end

  def logout
    session[:tenant_api_key] = nil
    redirect_to login_path
  end

  def index
    @chart_values = {}
    @chart_values["Total Questions"] = @public_questions.length
    @chart_values["Total Answers"] = @public_answers.length
    @chart_values["Total Users"] = @users.length
    @chart_values["All Tenant Views"] = @all_tenant_views
  end

  private

  def tenant_params
    params.require(:tenant).permit(:name)
  end

  def all_data
    @public_questions = Question.not_private
    @public_answers = Answer.from_public_questions
    @users = User.all
    @all_tenant_views = Tenant.all_tenant_views
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :verify_tenant_api_key

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def url_for(options={})
    case options
    when String
      if @hash_of_additional_params.present? && options != "#"
        uri = Addressable::URI.new
        uri.query_values = @hash_of_additional_params

        options = options + (options.index('?').nil? ? '?' : '&') + uri.query
        options
      end
    when Hash
      if @hash_of_additional_params.present?
        options.reverse_merge(@hash_of_additional_params)
        options
      end
    else
      options
    end

    super
  end

  def format_date(date, default_format = "%B %d, %Y")
    return date.present? ? date.strftime(default_format) : nil
  end
end

app/helpers/website_helper.rb
module WebsiteHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.haml
%footer.footer.bg-light
  .container
    .row
      .col-lg-6.h-100.text-center.text-lg-left.my-auto
        %ul.list-inline.mb-2
          %li.list-inline-item
            = link_to "About", "#"
          %li.list-inline-item ⋅
          %li.list-inline-item
            = link_to "Contact", "#"
          %li.list-inline-item ⋅
          %li.list-inline-item
            = link_to "Terms of Use", "#"
          %li.list-inline-item ⋅
          %li.list-inline-item
            = link_to "Privacy Policy", "#"
        %p.text-muted.small.mb-4.mb-lg-0= "© Your #{ENV['APP_TITLE']} 2018. All Rights Reserved."
      .col-lg-6.h-100.text-center.text-lg-right.my-auto
        %ul.list-inline.mb-0
          %li.list-inline-item.mr-3
            %a{:href => "#"}
              = fa_icon "facebook-square", class: "fa-2x fa-fw"
          %li.list-inline-item.mr-3
            %a{:href => "#"}
              = fa_icon "twitter-square", class: "fa-2x fa-fw"
          %li.list-inline-item
            %a{:href => "#"}
              = fa_icon "instagram", class: "fa-2x fa-fw"

app/views/layouts/_navigation.haml
%nav.navbar.navbar-default.static-top
  = link_to ENV['APP_TITLE'], "#", class: "navbar-brand"
  - if session[:tenant_api_key].present?
    = link_to "Logout", logout_path, class: "btn btn-primary", method: :post

  -# - unless ["login"].include?(params[:action])
  -#   .navbar-default.sidebar{:role => "navigation"}
  -#     .sidebar-nav.navbar-collapse
  -#       %ul#side-menu.nav
  -#         %li.sidebar-search
  -#           .input-group.custom-search-form
  -#             %input.form-control{:placeholder => "Search...", :type => "text"}/
  -#             %span.input-group-btn
  -#               %button.btn.btn-default{:type => "button"}
  -#                 %i.fa.fa-search
  -#           / /input-group
  -#         %li
  -#           %a{:href => "index.html"}
  -#             %i.fa.fa-dashboard.fa-fw
  -#             Dashboard
  -#         %li
  -#           %a{:href => "#"}
  -#             %i.fa.fa-bar-chart-o.fa-fw
  -#             Charts
  -#             %span.fa.arrow
  -#           %ul.nav.nav-second-level
  -#             %li
  -#               %a{:href => "flot.html"} Flot Charts
  -#             %li
  -#               %a{:href => "morris.html"} Morris.js Charts
  -#           / /.nav-second-level
  -#         %li
  -#           %a{:href => "tables.html"}
  -#             %i.fa.fa-table.fa-fw
  -#             Tables
  -#         %li
  -#           %a{:href => "forms.html"}
  -#             %i.fa.fa-edit.fa-fw
  -#             Forms
  -#         %li
  -#           %a{:href => "#"}
  -#             %i.fa.fa-wrench.fa-fw
  -#             UI Elements
  -#             %span.fa.arrow
  -#           %ul.nav.nav-second-level
  -#             %li
  -#               %a{:href => "panels-wells.html"} Panels and Wells
  -#             %li
  -#               %a{:href => "buttons.html"} Buttons
  -#             %li
  -#               %a{:href => "notifications.html"} Notifications
  -#             %li
  -#               %a{:href => "typography.html"} Typography
  -#             %li
  -#               %a{:href => "icons.html"} Icons
  -#             %li
  -#               %a{:href => "grid.html"} Grid
  -#           / /.nav-second-level
  -#         %li
  -#           %a{:href => "#"}
  -#             %i.fa.fa-sitemap.fa-fw
  -#             Multi-Level Dropdown
  -#             %span.fa.arrow
  -#           %ul.nav.nav-second-level
  -#             %li
  -#               %a{:href => "#"} Second Level Item
  -#             %li
  -#               %a{:href => "#"} Second Level Item
  -#             %li
  -#               %a{:href => "#"}
  -#                 Third Level
  -#                 %span.fa.arrow
  -#               %ul.nav.nav-third-level
  -#                 %li
  -#                   %a{:href => "#"} Third Level Item
  -#                 %li
  -#                   %a{:href => "#"} Third Level Item
  -#                 %li
  -#                   %a{:href => "#"} Third Level Item
  -#                 %li
  -#                   %a{:href => "#"} Third Level Item
  -#               / /.nav-third-level
  -#           / /.nav-second-level
  -#         %li
  -#           %a{:href => "#"}
  -#             %i.fa.fa-files-o.fa-fw
  -#             Sample Pages
  -#             %span.fa.arrow
  -#           %ul.nav.nav-second-level
  -#             %li
  -#               %a{:href => "blank.html"} Blank Page
  -#             %li
  -#               %a{:href => "login.html"} Login Page
  -#           / /.nav-second-level
  -#     / /.sidebar-collapse

app/views/layouts/application.haml
!!!
%html
  %head
    %title= ENV['APP_TITLE']
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/navigation"
    = yield
    = render "layouts/footer"

app/views/website/_heading_totals.haml
.row
  .col-lg-3.col-md-6
    .panel.panel-primary
      .panel-heading
        .row
          .col-xs-3
            = fa_icon "comments", class: "fa-5x"
          .col-xs-9.text-right
            .huge= @public_questions.length
            %div= "Total Questions"
      .panel-footer= raw "&nbsp;"

  .col-lg-3.col-md-6
    .panel.panel-green
      .panel-heading
        .row
          .col-xs-3
            = fa_icon "address-card", class: "fa-5x"
          .col-xs-9.text-right
            .huge= @public_answers.length
            %div= "Total Answers"
      .panel-footer= raw "&nbsp;"

  .col-lg-3.col-md-6
    .panel.panel-yellow
      .panel-heading
        .row
          .col-xs-3
            = fa_icon "users", class: "fa-5x"
          .col-xs-9.text-right
            .huge= @users.length
            %div= "Total Users"
      .panel-footer= raw "&nbsp;"

  .col-lg-3.col-md-6
    .panel.panel-red
      .panel-heading
        .row
          .col-xs-3
            = fa_icon "eye", class: "fa-5x"
          .col-xs-9.text-right
            .huge= @all_tenant_views
            %div= "All Tenant Views"
      .panel-footer= raw "&nbsp;"

app/views/website/_pie_chart_totals.haml
.panel.panel-default
  .panel-heading
    = fa_icon "bar-chart-o", class: "fa-fw"
    = "Pie Chart"
  .panel-body
    = pie_chart @chart_values, colors: ["#337ab7", "#5cb85c", "#f0ad4e", "#d9534f"]

app/views/website/_users_list.haml
.panel.panel-default
  .panel-heading
    = fa_icon "users", class: "fa-fw"
    = "Users"
  .panel-body
    .list-group
      - @users.each do |user|
        %li.list-group-item
          = user.name

app/views/website/index.haml
#wrapper
  .row
    .col-lg-12
      %h1.page-header= "Dashboard"

  = render "website/heading_totals"

  #dashboard_container
    .row
      .col-lg-8
        = render "website/pie_chart_totals"


        - if @public_questions.present?
          .panel.panel-default
            .panel-heading
              = fa_icon "comments", class: "fa-fw"
              = "Questions"
            .panel-body
              .list-group
                - @public_questions.each_with_index do |question, idx|
                  - position = idx + 1
                  - question_answers = question.answers
                  %li.list-group-item
                    .margin-bottom-half
                      %b= "#{position}."
                      = question.title
                      = link_to "#", class: "question-answers-button", data: {question_id: question.id} do
                        = fa_icon "chevron-down", class: "fa-fw"
                    %ul.question-answers{data: {question_id: question.id}}
                      - if question_answers.present?
                        - question_answers.each do |answer|
                          %li
                            %b= answer.user.name
                            = "-"
                            = answer.body
                      - else
                        %li
                          .alert.alert-danger= "No answers yet."

      .col-lg-4
        = render "website/users_list"

app/views/website/login.haml
%header.masthead.text-white.text-center
  .overlay
  .container
    .row
      .col-xl-9.mx-auto
        %h1.mb-5= "Build a landing page for your business or project and generate more leads!"
      .col-md-10.col-lg-8.col-xl-7.mx-auto
        = simple_form_for(:tenant, url: submit_login_website_index_path) do |f|
          .form-row
            .col-12.col-md-9.mb-2.mb-md-0
              = f.input :name, label: false, wrapper: false, placeholder: "Enter your name...", input_html: {class: "input-lg"}
            .col-12.col-md-3
              = f.submit "Sign In", class: "btn btn-block btn-lg btn-primary"